### PR TITLE
Fix the demo for ksqldb 0.10.0

### PR DESCRIPTION
**Pull request by AlanConfluent**
This fixes the ksql queries to comply with new changes to the "key" attribute of the WITH clause when creating tables.

### CODE REVIEW

**Comment by rspurgeon** [comment]
@AlanConfluent Thank you for the contribution!  We could test this against 6.0 nightly builds, assuming that contains ksqlDB server >= .10, however, this will need to be rebased off 6.0.x as of right now the parent commit is the 5.5.1-post branch HEAD.  That means utils/config.env contains the 5.5.1 values and that's what drives versions across most of the examples.

**Comment by ybyzek** [comment]
@AlanConfluent  @big-andy-coates already did https://github.com/confluentinc/examples/pull/670/files for 6.0.x, so is this PR still needed?

**Comment by big-andy-coates** [comment]
I think this can be closed. @AlanConfluent ?

**Comment by ybyzek** [comment]
@AlanConfluent I am closing this PR.  If you think this is in error, please let me know.

**Pull request closed without merging**
