### PR TITLE
Fix use of 'long' in clickstream.

### PR DESCRIPTION
**Pull request by big-andy-coates**
'Long' is not a valid data type for KSQL. Switching to 'BigInt'.

### CODE REVIEW

**Comment by big-andy-coates** [comment]
BTW, why do we have two copies of the clickstream demo? One each in KSQL and quickstart-demo repos?

https://github.com/confluentinc/quickstart-demos/pull/41

**Comment by big-andy-coates** [comment]
I've updated the SQL file inline with the KSQL repo version. This included dropping one of the statements, as it was causing an error:

> Windowing not supported run script 'ksql-clickstream-demo/demo/clickstream-schema.sql';for table aggregations

**Comment by ybyzek** [comment]
> BTW, why do we have two copies of the clickstream demo? One each in KSQL and quickstart-demo repos?

@big-andy-coates : the reason is that the one in KSQL is Docker only and the one in quickstart-demo is local install only

To avoid copying edits in two different places, we have some options:

Option 1: `start.sh` script does a `git clone` of ksql repo to get clickstream demo code
Option 2: move clickstream demo (Docker version) from `ksql` to `quickstart-demos` repo

Open to discussion.  cc: @rmoff

**Comment by big-andy-coates** [comment]
I'd go with option 1, as the docker images are built of the Ksql repo, so we'd then only have one copy of things, where as if you were to go with option 2 we'd still need a copy of things in the KSQL repo to build the docker images from, and there'd be another copy in this repo.

Also, keeping it all in KSQL means its much more likely engineers with fix up the SQL when/if changing things as they may be find it when searching the repo for other uses.

BTW: the KSQL repo still covers non-docker too: https://github.com/confluentinc/ksql/blob/9d39ff8a74e237389bf70e6ca1fcca136c13445e/ksql-clickstream-demo/non-docker-clickstream.md

**Comment by big-andy-coates** [comment]
Oh, and also, I don't have rights to merge into this repo. So you'll either need to give me permission or merge this for me :D

**Comment by rmoff** [comment]
For info, this is related: https://github.com/confluentinc/ksql/pull/1875

This breaks the clickstream demo out of a single Docker image and into a docker-compose deploy.

**Comment by ybyzek** [comment]
@rmoff , do you have thoughts on https://github.com/confluentinc/quickstart-demos/pull/41#issuecomment-422086438 ?

**Review by ybyzek — APPROVED** [review]
@big-andy-coates  : how to consolidate/de-dupe the Docker and non-Docker versions of the demo is bigger than this PR and should be discussed separately.

For now, changes LGTM

**Review by ybyzek — CHANGES_REQUESTED** [review]
Sorry, I approved changes but please submit against `5.0.0-post` branch instead of `master`, assuming the changes need to apply there.

**Comment by rmoff** [comment]
> @rmoff , do you have thoughts on [#41 (comment)](https://github.com/confluentinc/quickstart-demos/pull/41#issuecomment-422086438) ?

Yes, detailed in https://confluentinc.atlassian.net/browse/DEVX-289

**Comment by rmoff** [comment]
Just noticed that this hasn't been merged yet, which means that the bug is still present for anyone running the non-Docker version of this in `5.0.1-post`

`ksql> run script './ksql/ksql-clickstream-demo/demo/clickstream-schema.sql';io.confluent.ksql.parser.exception.ParseFailedException: Exception while processing statements :Source CLICKSTREAM does not exist.`

@ybyzek / @big-andy-coates can we get the fix merged in ?

**Comment by ybyzek** [comment]
@rmoff, @big-andy-coates  : please note my earlier comment about the branch into which you want to merge.  Right now the PR is set to merge into `master`, which is not validated and will not propagate to the default branch users get when they clone.  You need to reset to the appropriate branch (5.0.0-post?  5.0.1-post?) and rebase your code if needed

**Comment by rmoff** [comment]
I'm going to close this PR as I'm going to fix the issue as part of migrating code all into a single place.

**Pull request closed without merging**
