### PR TITLE
DEVX-2510: Reorders email service startup

### PR DESCRIPTION
**Pull request by rspurgeon**
### Description 

Email service has upstream dependencies, these minor changes
just help to ensure topics and data are running prior to starting
the service

### Author Validation

- [X] microservices-orders (ccloud and docker both)

### Reviewer Tasks
- [ ] microservices-orders (ccloud and docker both)

### CODE REVIEW

**Comment by ybyzek** [comment]
@rspurgeon in my env, still hitting the same issue:

```
-----InventoryService-store-of-reserved-stock-changelog topic-----
[2021-02-22 18:00:01,948] WARN The configuration 'replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:00:01,948] WARN The configuration 'basic.auth.credentials.source' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:00:01,949] WARN The configuration 'schema.registry.url' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:00:01,949] WARN The configuration 'ksql.basic.auth.user.info' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:00:01,949] WARN The configuration 'ksql.endpoint' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:00:01,949] WARN The configuration 'schema.registry.basic.auth.user.info' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
UNDERPANTS	1
UNDERPANTS	2
UNDERPANTS	3
UNDERPANTS	4
UNDERPANTS	5
Processed a total of 5 messages

-----platinum topic-----
[2021-02-22 18:00:18,116] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$:45)
org.apache.kafka.common.errors.TimeoutException
[2021-02-22 18:00:18,116] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$:45)
org.apache.kafka.common.errors.TimeoutException
Processed a total of 0 messages

```

**Comment by rspurgeon** [comment]
> @rspurgeon in my env, still hitting the same issue:
> 
Hmm, 3 consecutive runs for me without the issue.  I'll look into extending the timeout on the scripted consumer

```
-----InventoryService-store-of-reserved-stock-changelog topic-----
[2021-02-22 18:43:09,322] WARN The configuration 'replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:43:09,322] WARN The configuration 'basic.auth.credentials.source' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:43:09,323] WARN The configuration 'schema.registry.url' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:43:09,323] WARN The configuration 'ksql.basic.auth.user.info' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:43:09,323] WARN The configuration 'ksql.endpoint' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 18:43:09,323] WARN The configuration 'schema.registry.basic.auth.user.info' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
JUMPERS 1
JUMPERS 2
JUMPERS 3
JUMPERS 4
JUMPERS 5
Processed a total of 5 messages

-----platinum topic-----
{"id":"2","customerId":3,"customerLevel":"platinum"}
{"id":"2","customerId":3,"customerLevel":"platinum"}
{"id":"36","customerId":3,"customerLevel":"platinum"}
{"id":"36","customerId":3,"customerLevel":"platinum"}
{"id":"83","customerId":1,"customerLevel":"platinum"}
Processed a total of 5 messages
```

**Comment by rspurgeon** [comment]
@ybyzek can you try running with 9d3f2ea to see if that resolves the issue for you please?

**Comment by ybyzek** [comment]
Same issue.

```
[16:05:37] ~/git/examples/microservices-orders(DEVX-2510) ✗: git log
commit 9d3f2ea8781a47a03a0a75c572f65ae7786044e6 (HEAD -> DEVX-2510, origin/DEVX-2510)
Author: Rick Spurgeon <rspurgeon@users.noreply.github.com>
Date:   Mon Feb 22 13:15:00 2021 -0600

    DEVX-2510: extend timeout on platinum topic verification step
```

```
-----InventoryService-store-of-reserved-stock-changelog topic-----
[2021-02-22 21:04:24,872] WARN The configuration 'replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 21:04:24,873] WARN The configuration 'basic.auth.credentials.source' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 21:04:24,873] WARN The configuration 'schema.registry.url' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 21:04:24,873] WARN The configuration 'ksql.basic.auth.user.info' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 21:04:24,873] WARN The configuration 'ksql.endpoint' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
[2021-02-22 21:04:24,874] WARN The configuration 'schema.registry.basic.auth.user.info' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
UNDERPANTS	1
UNDERPANTS	2
UNDERPANTS	3
UNDERPANTS	4
UNDERPANTS	5
Processed a total of 5 messages

-----platinum topic-----
[2021-02-22 21:05:01,187] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$:45)
org.apache.kafka.common.errors.TimeoutException
[2021-02-22 21:05:01,187] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$:45)
org.apache.kafka.common.errors.TimeoutException
Processed a total of 0 messages

-----Query ksqlDB-----

-----orders_enriched stream (expect approximately 10 seconds)-----
[{"header":{"queryId":"_confluent-ksql-pksqlc-7yg61transient_1739850113167645398_1614027902507","schema":"`CUSTOMERID` BIGINT, `FIRSTNAME` STRING, `LASTNAME` STRING, `LEVEL` STRING, `PRODUCT` STRING, `QUANTITY` INTEGER, `PRICE` DOUBLE"}},
{"row":{"columns":[5,"Monica","Brown","gold","JUMPERS",1,1.0]}},
{"row":{"columns":[5,"Monica","Brown","gold","JUMPERS",1,1.0]}},
{"finalMessage":"Limit Reached"}]
```

**Review by ybyzek — APPROVED** [review]
@rspurgeon tested in my env, LGTM

**Pull request merged**
