### PR TITLE
DEVX-2664: Update assets/examples from kafkacat to kcat

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

Rename kafkacat to kcat (https://github.com/edenhill/kcat is available on brew now)

Sister PR: https://github.com/confluentinc/docs-platform/pull/1051

_What behavior does this PR change, and why?_

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] Documentation
- [x] kcat example

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Comment by ybyzek** [comment]
@confluentinc/docs this PR will rename a file.  Do we need a redirect added somewhere?

**Comment by londoncalling** [comment]
> @confluentinc/docs this PR will rename a file. Do we need a redirect added somewhere?

@ybyzek Yes, I will figure out where you need to add the redirect line and post here as soon as I get a chance.

**Review by edenhill — APPROVED** [review]
LGTM

**Review by londoncalling — APPROVED** [review]
LGTM

**Comment by ybyzek** [comment]
@londoncalling before merging, presumably we need an action on https://github.com/confluentinc/examples/pull/1021#issuecomment-916980311 ?

**Comment by londoncalling** [comment]
> @londoncalling before merging, presumably we need an action on [#1021 (comment)](https://github.com/confluentinc/examples/pull/1021#issuecomment-916980311) ?

Oh yes, you need a redirect. Do you want me to pull down your branch on https://github.com/confluentinc/examples/pull/1021#issuecomment-916980311 and add it for you, or me to tell you how to do it? It's in `conf.py`.

**Comment by ybyzek** [comment]
Ah, great.  I will look into conf.py and figure it out ;)

**Comment by londoncalling** [comment]
> Ah, great. I will look into conf.py and figure it out ;)

Just so I understand correctly, you want this: `https://docs.confluent.io/platform/current/tutorials/examples/clients/docs/kafkacat.html` to change to this, right? `https://docs.confluent.io/platform/current/tutorials/examples/clients/docs/kcat.html`

You should add the following line to the redirects in docs-platform:

`'tutorials/examples/clients/docs/kafkacat.html':'kcat.html',`

This is because it's going to a file in the same directory, so you should not need all the other prefix paths on the right side, and in fact I think those will make it break.

It _should_ work similar this other redirect that's above in the same file:

`'schema-registry/singledc.html':'multidc.html',`

We can test it once you push the change to the PR, before we merge it.

**Pull request merged**
