### PR TITLE
Update master to Kafka trunk (commit d5c821c), CP 3.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by miguno**

### CODE REVIEW

**Comment by miguno** [comment]
Please review anyOf @mjsax @dguy @guozhangwang @enothereska .

**Comment by dguy** [comment]
LGTM - though the build is failing on trying to pull in one of the confluent dependencies

**Comment by miguno** [comment]
@dguy : Yeah, that's an unfortunate general problem with our `master` branch and its build setup.  There are no public snapshot artifacts yet which the Travis CI build could use for the build.

**Comment by enothereska** [comment]
LGTM, but why are checks failing?

**Comment by miguno** [comment]
@enothereska : see my comment https://github.com/confluentinc/examples/pull/50#issuecomment-235945280

**Pull request merged**
