### PR TITLE
DEVX-1689 Removes eclipse plugin and deprecated functions from SR example code

### PR DESCRIPTION
**Pull request by rspurgeon**
@londoncalling In addition to removing the eclipse plugin from this example, I also removed some deprecated code.   Please verify, I believe that these changes will require a docs change in the following places:
https://docs.confluent.io/current/schema-registry/schema_registry_tutorial.html#example-producer-code
https://docs.confluent.io/current/schema-registry/schema_registry_tutorial.html#example-producer-code

### CODE REVIEW

**Comment by londoncalling** [comment]
Thanks, @rspurgeon , this is great. I'll walk through it today.

**Comment by rspurgeon** [comment]
Also @londoncalling , as you mentioned in DEVX-1689, the docs will need to update based on the output of the ConsumerExample:```


key = id0, value = {"id": "id0", "amount": 1000.0}
key = id1, value = {"id": "id1", "amount": 1000.0}
key = id2, value = {"id": "id2", "amount": 1000.0}
key = id3, value = {"id": "id3", "amount": 1000.0}
key = id4, value = {"id": "id4", "amount": 1000.0}
key = id5, value = {"id": "id5", "amount": 1000.0}
key = id6, value = {"id": "id6", "amount": 1000.0}
key = id7, value = {"id": "id7", "amount": 1000.0}
key = id8, value = {"id": "id8", "amount": 1000.0}
key = id9, value = {"id": "id9", "amount": 1000.0}
```

**Comment by londoncalling** [comment]
@rspurgeon , okay, great, I have a PR open to make these follow up changes to the docs (https://github.com/confluentinc/docs/pull/4188), I'll tag you on it when the tutorial aspect of it is ready to review.

**Comment by londoncalling** [comment]
@rspurgeon , you are now tagged on https://github.com/confluentinc/docs/pull/4188, direct links to the SR tutorial topics to review are in the description of the PR. The examples work great with your code changes, thanks!

**Comment by rspurgeon** [comment]
@ybyzek the docs PR above is under review, can you please review this for me so we can merge?  TY

**Review by ybyzek — APPROVED** [review]
LGTM

**Pull request merged**
