### PR TITLE
DEVX-2078: MRC demo cannot be upgraded to 6.0.0 (UBI) due to lack of tc installed on Docker images

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-2078

_What behavior does this PR change, and why?_

- 6.0.0 ubi images do not have `tc` installed by default
- Installs and directly configures `tc` on the containers.
- Removes Pumba (pro: one fewer dependency; con: more tc commands)

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] Documentation

- [x] multiregion

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

- [x] multiregion

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

**Review by awalther28 — APPROVED** [review]
I was pretty excited to see this PR, thank you @ybyzek ! I ran through the multiregion tutorial on 6.0.0-post and on your branch (DEVX-2078), both producer/consumer times seemed roughly the same. The failover and failback scenarios went as expected. Overall I approve.

**Comment by ybyzek** [comment]
@awalther28 thanks!  It occurred to me that `tc` install might not be required on the containers afterall, if we're using the `--tc-image` flag with Pumba, and I'm testing this out now but not seeing the behavior I expect.  I'll keep fiddling with this and see if I can simplify the PR...will get back to you soon.

**Comment by ybyzek** [comment]
@awalther28 when you have a chance, would you please run the example again?  It's changed quite a bit since you last ran it

**Comment by awalther28** [comment]
@ybyzek I ran through it this morning. I think using tc + docker networking better highlights message latency between "regions". My approval still stands. Thank you for battling docker networking and finding a solid solution.

**Comment by ybyzek** [comment]
Thanks @awalther28 .  I also validated local docs build, so will go ahead and merge now.

**Pull request merged**
