### PR TITLE
align C3 RBAC configs with rest of CP

### PR DESCRIPTION
**Pull request by brianbushree**
sync with https://github.com/confluentinc/blueway/pull/1978

### CODE REVIEW

**Review by ybyzek — COMMENTED** [review]
@brianbushree thank you so much for the PR!  LGTM.  Before merging, can you please confirm you have validated the changes?  Thanks in advance.

**Comment by brianbushree** [comment]
Will do!

It needs to be synced with two other changes so I'll let you know when I get it tested

**Comment by ybyzek** [comment]
Thanks @brianbushree .  So I will wait for validation confirmation before merging.

**Comment by brianbushree** [comment]
yes please 👍

**Comment by brianbushree** [comment]
@ybyzek just waiting on a 5.4.0 docker image to come out...

also it seems like we need to do some `5.3` -> `5.4` refactor before this will run

**Comment by ybyzek** [comment]
> also it seems like we need to do some 5.3 -> 5.4 refactor before this will run

@brianbushree will the refactoring that you are referring to be addressed by @sdanduConf 's PR https://github.com/confluentinc/examples/pull/345 ?  Or is there other refactoring to be done?

**Comment by ybyzek** [comment]
@brianbushree I propose we close this PR in favor of https://github.com/confluentinc/examples/pull/372/files [WIP] which has consolidated RBAC changes, some of which are dependencies for C3 to work.  That PR already has applied the C3 changes from this PR

**Comment by brianbushree** [comment]
💯

thanks for taking this over @ybyzek!

**Pull request closed without merging**
