### PR TITLE
DEVX-2562: Issues with REST Proxy example to Confluent Cloud

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-2562

_What behavior does this PR change, and why?_

- Fix REST Proxy example
- Changes to SR parameter names, impacts `ccloud-stack` and all examples

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] Documentation: https://github.com/confluentinc/docs-platform/pull/527

- [x] ccloud/ccloud-stack

- [ ] clients/cloud: rest-proxy, java

- [ ] cp-quickstart: cloud version

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

**Comment by mikebin** [comment]
Does this command work for you (step 4 in setup):

```
../../../ccloud/ccloud-generate-cp-configs.sh $HOME/.confluent/java.config
```

I had to switch to `examples/ccloud`.

**Comment by ybyzek** [comment]
@mikebin this works.  Am I doing something different from the docs?

```
[20:33:49] ~/git/examples(DEVX-2562): cd clients/cloud/rest-proxy/
[20:33:50] ~/git/examples/clients/cloud/rest-proxy(DEVX-2562): ../../../ccloud/ccloud-generate-cp-configs.sh $HOME/.confluent/java.config
```

**Comment by mikebin** [comment]
Probably just an issue on my side, but when I run this command:

```
../../../ccloud/ccloud-generate-cp-configs.sh $HOME/.confluent/java.config
```
here's what I get:
```
../../../ccloud/ccloud-generate-cp-configs.sh: line 6: ../utils/ccloud_library.sh: No such file or directory
../../../ccloud/ccloud-generate-cp-configs.sh: line 8: ccloud::generate_configs: command not found
```

**Comment by mikebin** [comment]
Sorry, I wasn't on the right branch for the PR. Looks good.

**Review by rspurgeon — APPROVED** [review]
LGTM, demo worked.  I think at some point we should take the additional step of renaming the variable `SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO` to match the new configuration in ccloud_library generate_configs function

**Comment by ybyzek** [comment]
> LGTM, demo worked. I think at some point we should take the additional step of renaming the variable `SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO` to match the new configuration in ccloud_library generate_configs function

@rspurgeon there is actually a specific reason this hasn't been done yet -- please see https://confluentinc.atlassian.net/browse/DEVX-2255 .  I didn't dig into it very deeply (so please correct me @mikebin if I am mistaken) but it appears that some CP components still require the `schema.registry.` (i.e. `SCHEMA_REGISTRY_`) prefix.  So there's no real drive to change the variable name until all components use the same one.

**Pull request merged**
