### PR TITLE
Rename Confluent Cloud UI to Confluent Cloud Console

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

_What behavior does this PR change, and why?_

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] Documentation -- I validated docs build locally

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM

**Comment by vsyu** [comment]
For the URLs, are we using https://confluent.cloud/login because the user likely already has an account? https://www.confluent.io/confluent-cloud/tryfree/ is generally the preferred link, but understandably in some cases it may not be appropriate. 

I checked with Leslie on the shorthand for "Confluent Cloud Console" as well. She shared: "The Docs rule is that the first time in blog/ page we should use the full name 'Confluent Cloud Console' and the we can refer to it as 'Cloud Console' for an abbreviated format.

**Comment by ybyzek** [comment]
@vsyu thanks for the feedback, and I agree.  I have updated links as needed in the latest commit.

**Comment by vsyu** [comment]
Thanks for the updates, @ybyzek! The only other suggestion would be to update line 225 to point to https://www.confluent.io/confluent-cloud/tryfree/ instead of https://confluent.cloud/.

**Comment by ybyzek** [comment]
@vsyu that line is intentionally pointing to https://confluent.cloud/.  The user by this point has already been shown the `tryfree` link and the intention is to send them now to the console itself :)

**Comment by vsyu** [comment]
@ybyzek ah, good to know! Makes sense :)

**Pull request merged**
