### PR TITLE
DEVX-2403: ccloud-stack error if environment does not exist

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-2403

_What behavior does this PR change, and why?_

Fail fast if environment does not exit

```
$ ENVIRONMENT=dummy ./ccloud_stack_create.sh
....

Creating Confluent Cloud stack for service account demo-app-8408, ID: 163253.
Error: environment "dummy" not found

Suggestions:
    List available environments with `ccloud environment list`.

```

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] ccloud/ccloud-stack

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

- [ ] ccloud/ccloud-stack

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM, tested with:
```
➜ (source ccloud_library.sh; ENVIRONMENT=abc123 ccloud::create_ccloud_stack)
Creating Confluent Cloud stack for service account demo-app-15979, ID: 169096.
Error: environment "abc123" not found

Suggestions:
    List available environments with `ccloud environment list`.

```

**Comment by rspurgeon** [comment]
> LGTM, tested with:
> 
> ```
> ➜ (source ccloud_library.sh; ENVIRONMENT=abc123 ccloud::create_ccloud_stack)
> Creating Confluent Cloud stack for service account demo-app-15979, ID: 169096.
> Error: environment "abc123" not found
> 
> Suggestions:
>     List available environments with `ccloud environment list`.
> ```

FYI: I'm pretty sure the error message from `ccloud enviornment use` is returned on stderr, so the value of $OUTPUT in the error case is an empty string.   Since this doesn't "swallow" stderr, the value of OUTPUT is basically irrelevant and the user will observe the stderr output.

I believe the following results in the same behavior for the user:

    `ccloud environment use $ENVIRONMENT || { exit 1; }`

**Comment by ybyzek** [comment]
@rspurgeon good catch on the stderr.

For clarification, would this simplified line be preferable:

```
ccloud environment use $ENVIRONMENT || exit 1
```

Specifically, I'm not sure the value of the backticks or `{}`

**Comment by rspurgeon** [comment]
> @rspurgeon good catch on the stderr.
> 
> For clarification, would this simplified line be preferable:
> 
> ```
> ccloud environment use $ENVIRONMENT || exit 1
> ```
> 
> Specifically, I'm not sure the value of the backticks or `{}`

Yeah, the brackets and semicolon are unecessary... that was my quick edit from the original ;-)

**Comment by ybyzek** [comment]
@rspurgeon does the new edit look ok?

**Review by rspurgeon — APPROVED** [review]
LGTM

**Pull request merged**
