### PR TITLE
DEVX-1824: follow-on to rename library

### PR DESCRIPTION
**Pull request by ybyzek**
Follow-up to https://github.com/confluentinc/examples/pull/645

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM

**Review by rspurgeon — APPROVED** [review]
LGTM

**Comment by ybyzek** [comment]
@rspurgeon  I made substantial changes after your approval (my apologies).  When you have the chance, would you mind reviewing the updated changes?

**Comment by ybyzek** [comment]
@rspurgeon note that helper.sh no longer has `source "$DIR/helper_cloud.sh"`, which is sourced independently.

**Review by rspurgeon — APPROVED** [review]
LGTM

note: Just a visual review, I cannot test all the exampls this touches

**Pull request merged**
