### PR TITLE
upgrade avro 1.8.0

### PR DESCRIPTION
**Pull request by mageshn**

### CODE REVIEW

**Comment by miguno** [comment]
@mageshn: Question, what's the motivation for the Avro version bump?  (We want to stay in-sync with e.g. the Avro version used by Confluent schema registry.)  Also, why "only" 1.8.0?  The latest version is IIRC 1.8.2.

I found e.g. the pending PR at https://github.com/confluentinc/schema-registry/pull/563.

**Comment by mageshn** [comment]
upgrading avro to 1.8.2 inline with SR avro upgrade

**Comment by mageshn** [comment]
@miguno i have upgraded it to 1.8.2 now. The SR avro version is also getting upgraded to 1.8.2 and hence this change.

**Comment by ewencp** [comment]
@miguno Yes, we want things to stay aligned and there have been frequent requests for 1.8 support in serdes.

**Pull request merged**
