### PR TITLE
.net client -> v1.0

### PR DESCRIPTION
**Pull request by mhowlett**

### CODE REVIEW

**Comment by mhowlett** [comment]
@ybyzek

**Comment by ybyzek** [comment]
@mhowlett , could you also update https://github.com/confluentinc/examples/blob/5.2.1-post/clients/cloud/csharp/README.md#prerequisites to add a bullet point, something along the lines of:

> Confluent's .NET Client for Apache Kafka installed on your machine. Check that you are using version 1.0.0 or higher (e.g., ...provide command to view version...)

As is similarly done for Python at https://github.com/confluentinc/examples/blob/5.2.1-post/clients/cloud/python/README.md#prerequisites

**Review by ybyzek — APPROVED** [review]
LGTM, thanks @mhowlett

**Comment by ybyzek** [comment]
@mhowlett this PR has been open a while.  I was wondering if it’s still up-to-date (and can be merged) or does it need a refresh (and should not be merged)?

**Comment by mhowlett** [comment]
yes, fine to merge. We're at v1.2.1 now, but it doesn't really matter. I don't think it makes sense to add a bullet point along the lines of that suggested since the client just a dependency of the project.

**Pull request merged**
