### PR TITLE
DEVX-1564 local demos now verify full CP version

### PR DESCRIPTION
**Pull request by rspurgeon**
Tested w/ music demo

### CODE REVIEW

**Review by ybyzek — CHANGES_REQUESTED** [review]
This fails in 5.5.x branch because `${CP_VERSION_FULL}` is `5.5.0` but confluent local version is `5.5.0-SNAPSHOT`.

**Comment by rspurgeon** [comment]
> This fails in 5.5.x branch because `${CP_VERSION_FULL}` is `5.5.0` but confluent local version is `5.5.0-SNAPSHOT`.

Thank you.  I've staged changes to make these use the `CONFLUENT` version, however that prevents the 5.5.x branch from working until there are 5.5.1-SNAPSHOT|latest artifacts available.

**Comment by rspurgeon** [comment]
@ybyzek I've re-targeted this to 5.5.0-post and updated to use the CONFLUENT variable.  Please re-review at your convenience.  TY

**Review by ybyzek — APPROVED** [review]
@rspurgeon LGTM.  I also looked at parameters for 5.5.x branch and it looks good because `CONFLUENT` says 5.5.1-SNAPSHOT which is what I expect the CLI to show as well.

**Pull request merged**
