### PR TITLE
Typo error corrected in the pageviewregion.avsc file

### PR DESCRIPTION
**Pull request by Kamal15**

### CODE REVIEW

**Comment by Kamal15** [comment]
@miguno @guozhangwang 

Call for review.

**Comment by Kamal15** [comment]
clabot:check

**Comment by Kamal15** [comment]
[clabot:check]

**Comment by ewencp** [comment]
ok to test

**Comment by mjsax** [comment]
As we are going to move over to https://github.com/confluentinc/kafka-streams-examples pumping the version to 3.4 does not make sense. There are also many conflicts. Please resolve before we can review.

**Comment by Kamal15** [comment]
@mjsax 
closed this PR and opened a new PR in the https://github.com/confluentinc/kafka-streams-examples repo. 
PR: https://github.com/confluentinc/kafka-streams-examples/pull/6

**Comment by mjsax** [comment]
Thanks @Kamal15 !

**Pull request closed without merging**
