### PR TITLE
DEVX-988 - Add RST landing page for demos

### PR DESCRIPTION
**Pull request by joel-hamill**
https://confluentinc.atlassian.net/browse/DEVX-988
- related https://github.com/confluentinc/docs/pull/2411

### CODE REVIEW

**Comment by ybyzek** [comment]
@joel-hamill thanks for the PR.

A few clarification questions:

1. Is `index.rst` intended to be used only in docs.confluent.io?
2. Does this mean we have to make equivalent changes in two places now: index.rst and README.md, whenever something is updated in either?
3. Should the GH links mentioned index.rst point to `|release|` instead of `5.3.0-post`?

**Comment by joel-hamill** [comment]
@ybyzek 
Is index.rst intended to be used only in docs.confluent.io?
> yes.  i'm open to other ideas?
Does this mean we have to make equivalent changes in two places now: index.rst and README.md, whenever something is updated in either?
> yes
Should the GH links mentioned index.rst point to |release| instead of 5.3.0-post?
> yeah that would make sense - except in that table (which i sloppily transferred as HTML, that won't work).

**Comment by joel-hamill** [comment]
@ybyzek any more thoughts on this?

**Comment by joel-hamill** [comment]
closing per discussion with @ybyzek

**Pull request closed without merging**
