### PR TITLE
DEVX-2119: Removing remainder ZK references where possible

### PR DESCRIPTION
**Pull request by ybyzek**

### CODE REVIEW

**Comment by ybyzek** [comment]
@thomaskwscott all feedback welcome, but in particular it would be helpful if you could kindly review/validate the PR changes to the Replicator (a) schema translation and (b) security examples.

**Review by ghost — APPROVED** [review]
LGTM

**Comment by rspurgeon** [comment]
@ybyzek this change touches multiple demos simultaneously, are you looking for a review to include validating each change for each demo?

**Comment by ybyzek** [comment]
> @ybyzek this change touches multiple demos simultaneously, are you looking for a review to include validating each change for each demo?

@rspurgeon I have validated all the demos except the ones noted to @thomaskwscott , so no need for you to validate.  It would be helpful if you could just read/review the code changes.

**Review by rspurgeon — APPROVED** [review]
LGTM syntactically, deleting code is fun

**Pull request merged**
