### PR TITLE
Fixed Exception caused by Empty Lines in config file.

### PR DESCRIPTION
**Pull request by JBeamer92**
### Description 

_What behavior does this PR change, and why?_

The config file provided in the C# setup contains empty lines with a Length of 0. This was causing Exceptions when trying to read the config file in the LoadConfig method because the empty lines were not being filtered out by the Where clause. By filtering out empty lines with a length of 0, the LoadConfig method completes without exceptions and the application completes as expected.

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._
Verified using .NET 6.0. Needs to be tested against earlier versions of .NET to prove backwards compatibility.

[ ] clients/cloud

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._
Needs to be tested against earlier versions of .NET to prove backwards compatibility.

[ ] clients/cloud

### CODE REVIEW

**Comment by ybyzek** [comment]
@bbejeck do you happen to have the right environment set up to validate this PR?

**Comment by bbejeck** [comment]
> do you happen to have the right environment set up to validate this PR?

Yes - I have .NET versions 3, 5, and 6 installed - I can test against all 3

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
Tested against .NET 6 and 5 - .NET 3 is pretty old and not compatible with `Confluent.Kafka 1.8.2` so IMHO going with version 5 is good enough

**Comment by ybyzek** [comment]
@bbejeck thanks so much for validating and @JBeamer92 thanks again for the PR!  Merging now

**Pull request merged**
