### PR TITLE
fix 447

### LINKED ISSUE #447: KSQL server cannot work with Kafka Connect container: Connect to localhost:8083 [localhost/127.0.0.1] failed: Connection refused
**Problem**:
When starting the Confluent Platform in Docker and working with connector related commands in KSQL-CLI, the following error occurs:

> io.confluent.ksql.util.KsqlServerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8083 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
> Caused by: org.apache.http.conn.HttpHostConnectException: Connect to
> 	localhost:8083 [localhost/127.0.0.1] failed: Connection refused (Connection
> 	refused)
> Caused by: Could not connect to the server.
> Caused by: Could not connect to the server.

**Reproduce**:

Start the confluent platform:

```bash
git clone https://github.com/confluentinc/examples
cd examples
git checkout 5.4.0-post
cd cp-all-in-one/
docker-compose up -d
```

Start KSQL-CLI:

```bash
docker run -it --rm --name ksql-cli-1 --network cp-all-in-one_default confluentinc/cp-ksql-cli:5.4.0 http://ksql-server:8088
```

Try to run list connectors & create a new connector:

```bash
list connectors;

CREATE SOURCE CONNECTOR example WITH(
    "connector.class"='FileStreamSource',
    "tasks.max"=1,
    "file"='/etc/hostname',
    "topic"='connect-test'
);
```

These commands fail with the error above

### PR DESCRIPTION
**Pull request by dvirf1**
This fixes #447 by adding an environment variable to KSQL server with Kafka Connect url

### CODE REVIEW

**Comment by ybyzek** [comment]
Thanks for the PR @dvirf1 .  Copying @confluentinc/ksql for review.

**Review by vcrfxia — APPROVED** [review]
LGTM

**Comment by vcrfxia** [comment]
Was going to add confluentinc/ksql back as a reviewer after my review in case other members of the team want to review as well but it seems I don't have permissions.

**Comment by ybyzek** [comment]
@vcrfxia I added @confluentinc/ksql back in for optional review.

**Comment by dvirf1** [comment]
@ybyzek, thanks for the super fast response (and to Victoria for the review).
Should I tag anyone specific from @confluentinc/ksql?

**Pull request merged**
