### PR TITLE
Bumping check style version

### PR DESCRIPTION
**Pull request by gAmUssA**
Github reports that 8.12 contains compromised transitive dependency. Need to upgrade

### CODE REVIEW

**Comment by gAmUssA** [comment]
wrt 
image

and 

image

**Review by ybyzek — CHANGES_REQUESTED** [review]
@gAmUssA -- thanks for submitting the PR. Have you run the examples to verify they still work with the version change?  I don't think we should merge this PR until it's verified

**Comment by gAmUssA** [comment]
@ybyzek do we strictly obey checkstyle checks?
Because checks require some code changes

**Comment by gAmUssA** [comment]
@ybyzek with 4903fdf I fixed checkstyle warnings

**Review by ybyzek — APPROVED** [review]
LGTM!  Thanks again @gAmUssA

**Pull request merged**
