### PR TITLE
DEVX-2222: ccloud_library cleans up ccloud usage for connectors

### PR DESCRIPTION
**Pull request by rspurgeon**
### Description 

Uses JSON processing for ccloud connector monitoring
https://confluentinc.atlassian.net/browse/DEVX-2222

### Author Validation

- [x] cp-quickstart (cloud)

### Reviewer Tasks
- [x] cp-quickstart (cloud)

### CODE REVIEW

**Comment by ybyzek** [comment]
Error on startup (same as https://github.com/confluentinc/examples/pull/855#issuecomment-719563438)

```
[9:53:04] ~/git/examples/cp-quickstart(DEVX-2222): ./start-cloud.sh 
✔ jq found
✔ ccloud version ok
✔ logged into ccloud CLI
✔ Prerequisite check pass

====== Confirm

This example uses real Confluent Cloud resources.
To avoid unexpected charges, carefully evaluate the cost of resources before launching the script and ensure all resources are destroyed after you are done running it.
Do you still want to run this script? [y/n] y
Do you acknowledge this script creates a Confluent Cloud KSQL app (hourly charges may apply)? [y/n] y

For your reference the demo will highlight some commands in code format

====== Starting


====== Creating new Confluent Cloud stack using the ccloud::create_ccloud_stack function
See: https://github.com/confluentinc/examples/blob/6.0.0-post/utils/ccloud_library.sh for details
Creating Confluent Cloud stack for service account demo-app-7499, ID: 132553.
Error: accepts 1 arg(s), received 42
Usage:
  ccloud kafka cluster describe <id> [flags]

Flags:
  -o, --output string   Specify the output format as "human", "json", or "yaml". (default "human")

Global Flags:
  -h, --help            Show help for this command.
  -v, --verbose count   Increase verbosity (-v for warn, -vv for info, -vvv for debug, -vvvv for trace).

Error: resource "Error" not found

Suggestions:
    Check that the resource "Error" exists.
    To list Kafka clusters, use `ccloud kafka cluster list`.
    To check schema-registry cluster info, use `ccloud schema-registry cluster describe`.
    To list KSQL clusters, use `ccloud ksql app list`.

Waiting up to 720 seconds for Confluent Cloud cluster to be ready and for credentials to propagate
```

**Comment by rspurgeon** [comment]
> Error on startup (same as [#855 (comment)](https://github.com/confluentinc/examples/pull/855#issuecomment-719563438))

@ybyzek please indicate your `ccloud` version, I do not get these errors on `v1.19.1`

**Comment by ybyzek** [comment]
@rspurgeon `v1.19.1`:

```
[10:13:23] ~/code: ccloud version
ccloud - Confluent Cloud CLI

Version:     v1.19.1
Git Ref:     d494fa6
Build Date:  2020-10-17T03:14:54Z
Go Version:  go1.14.7 (darwin/amd64)
Development: false

[10:13:26] ~/code: 
```

**Comment by rspurgeon** [comment]
> @rspurgeon `v1.19.1`:

Any chance you can debug?  My local setup does not encounter this issue:

```
./start-cloud.sh
✔ jq found
✔ ccloud version ok
✔ logged into ccloud CLI
✔ Prerequisite check pass

====== Confirm

This example uses real Confluent Cloud resources.
To avoid unexpected charges, carefully evaluate the cost of resources before launching the script and ensure all resources are destroyed after you are done running it.
Do you still want to run this script? [y/n] y
Do you acknowledge this script creates a Confluent Cloud KSQL app (hourly charges may apply)? [y/n] y

For your reference the demo will highlight some commands in code format

====== Starting


====== Creating new Confluent Cloud stack using the ccloud::create_ccloud_stack function
See: https://github.com/confluentinc/examples/blob/6.0.0-post/utils/ccloud_library.sh for details
Creating Confluent Cloud stack for service account demo-app-30162, ID: 132575.
Set Kafka cluster "lkc-9g2w7" as the active cluster for environment "env-d1151".

Waiting up to 720 seconds for Confluent Cloud cluster to be ready and for credentials to propagate
....
Sleeping an additional 80 seconds to ensure propagation of all metadata
...
```

**Review by ybyzek — APPROVED** [review]
@rspurgeon LGTM, wonderful improvement.

**Pull request merged**
