### PR TITLE
fixed Makefile-impl USER variable issue on some Cloud Shell Envrionments

### PR DESCRIPTION
**Pull request by jasonsmithio**
In some Cloud Shell setups, using $USER causes an error. I replaced the variable

### CODE REVIEW

**Comment by rspurgeon** [comment]
Thanks for the PR @TheJaySmith!  I'm curious which cloud shell environment you ran this on to surface the issue?

**Comment by jasonsmithio** [comment]
qwiklabs.com environment. We aren't sure why yet

**Comment by rspurgeon** [comment]
> qwiklabs.com environment. We aren't sure why yet

Thanks for the reply.  One thing I like about the usage of USER is that we may have multiple simultaneous runners of our demo targeting the same GCP project.   Any thoughts on a different way to distinquish demo runners that would work for your environment?

**Comment by jasonsmithio** [comment]
One issue is the character limit in GKE for cluster names. Our username for QwikLabs are long so tagging that onto an already lengthy cluster name exceeds the limit. Perhaps we can allow people to add their own tags to the cluster name?

**Comment by rspurgeon** [comment]
@TheJaySmith I'm going to close this for now, if we get another instance of the use of $USER being an issue I will revist an alternative approach.  Thanks

**Pull request closed without merging**
