### PR TITLE
Update OrderDetailsService.java

### PR DESCRIPTION
**Pull request by rocpoc**
A necessary addition for the tests to pass when following the microservices tutorial. If you look at the solutions file, this is included.

Thanks!

### CODE REVIEW

**Comment by ybyzek** [comment]
@rocpoc 

1. What is the error message without this PR?

2. What is the command you are running that generates that error?

3. Looking at the solution at https://github.com/confluentinc/kafka-streams-examples/blob/5.5.1-post/src/main/java/io/confluent/examples/streams/microservices/OrderDetailsService.java#L182-L190, these lines are not included.  So it's not clear what you mean by "If you look at the solutions file, this is included." -- can you please provide a link to what you are looking at?

cc: @rspurgeon

**Comment by ybyzek** [comment]
@rspurgeon note: the lines added into this PR were removed by https://github.com/confluentinc/kafka-streams-examples/pull/346, so could you look into this issue here?  Also, not sure if related or orthogonal, but please also see https://github.com/confluentinc/examples/pull/690#issuecomment-669936810

**Comment by rspurgeon** [comment]
@rocpoc Thanks for the PR.  I removed this code because the return value of `order.getCustomerId()` is a primative `long` and cannot be null, so the expression `customerId == null` can never be true.  There was an implicit cast between `long` and `Long` here.  I validated this could be removed with IDEA's code analyzer. 

Could you let me know what tests you ran where you see a failure?  Thanks

**Comment by rocpoc** [comment]
@rspurgeon thanks for the information!

Looking at my project files, I believe I was working off of the 5.5.0 Post branch. It had been just over a month since I checked on it, but after cloning the repository again, the files now work as intended and don't need any fixes. 

Someone must have fixed the issue in the last month and I didn't see it. Thanks!

**Pull request closed without merging**
