### PR TITLE
Move away from rule in scala

### PR DESCRIPTION
**Pull request by enothereska**

### CODE REVIEW

**Comment by enothereska** [comment]
@miguno @ijuma could you please check? If good I'll need to update all other scala tests. Doing ClassRule with scala is overly complicated and for these tests it's simpler to just have the usual before/after methods instead.

**Comment by miguno** [comment]
Why is this a problem @enothereska?  Using the ClassRule mimics what we are doing in Java, and it also leads to faster test runs because it prevents us from starting a new Kafka/Zk/schema-registry instances for every individual test.

**Comment by enothereska** [comment]
@miguno I agree that `ClassRule` is useful, but we didn't have it right. If you look at the Java code we had a combination of `ClassRule` with `BeforeClass`, whereas in the Scala code we had a `Rule` with `Before`, which is not correct IMO. If we want to have a ClassRule in Scala we'd have to declare an object class like this: http://randomallsorts.blogspot.co.uk/2012/11/junit-411-whats-new-rules.html.

Since we typically have just one test in the scala tests, I don't see the point of complicating the code with objects like that and a straightforward Before/After is simpler IMO.

**Comment by enothereska** [comment]
cc @dguy

**Comment by dguy** [comment]
I agree with @enothereska . In cases when there is only a single test in the class there is really no gain in having a class rule.

**Comment by enothereska** [comment]
So I don't think this necessarily fixes the problem we're seeing in Jenkins where every now and then an address is in use. It's more of a code shuffle. Still investigating.

**Pull request closed without merging**
