### PR TITLE
DEVX-1284: For pre-5.4 GA demos, pull in specific version of kafka-co…

### PR DESCRIPTION
**Pull request by ybyzek**
…nnect-datagen

I have validated one of the demos with this PR, specifically `cp-quickstart/start.sh`.

Related to future change: https://github.com/confluentinc/kafka-connect-datagen/pull/44

### CODE REVIEW

**Comment by C0urante** [comment]
@ybyzek the changes look acceptable, but have we considered using a substitution so that if the version needs to be adjusted in the future we'll only have to tweak one line and the chances of accidentally missing an occurrence of the version will be eliminated?

**Comment by ybyzek** [comment]
@C0urante 💯 agree with the suggestion.  But it'll take careful thought about how to implement this across all demos in the repo.  This suggestion will not be implemented in this PR but I have filed DEVX-1290 to track.  Thank you!

**Review by C0urante — APPROVED** [review]
LGTM

I'm a little embarrassed to admit it... but I thought this PR was for the docs repo, which already has its own RST substitution logic. Yeah, let's definitely save adding substitution logic to this repo for a separate issue/PR 😅

**Review by rspurgeon — APPROVED** [review]
LGTM, tested locally

**Pull request merged**
