### PR TITLE
minor changes in wikipedia elasticsearch config

### PR DESCRIPTION
**Pull request by nikesh0822**

### CODE REVIEW

**Comment by nikesh0822** [comment]
@ybyzek

**Comment by ybyzek** [comment]
@nikesh0822 thanks for the PR.  Is this PR meant to address DEVX-1433?  Can you please add a description to the PR and explain what it fixes?  Thanks!

**Comment by nikesh0822** [comment]
@ybyzek this PR addresses DEVX-1433 and fixes it by adding en_wikipedia_gt_i in elasticsearch config file (topic and topic.index.map params) to make sure the index is available for hits.

**Comment by ybyzek** [comment]
`wikipedia` example no longer in repo.  Please see Docker-based version of demo at https://docs.confluent.io/platform/current/tutorials/cp-demo/docs/index.html

**Pull request closed without merging**
