### PR TITLE
Fixes DEVX-802

### PR DESCRIPTION
**Pull request by gAmUssA**
Specific dependency/maven version.

Range version would use incompatible checkstyle version

### CODE REVIEW

**Review by ybyzek — APPROVED** [review]
LGTM! thanks

**Comment by ybyzek** [comment]
@gAmUssA -- should this target earlier release where previous PR went in?  Looks like it might be as early as 5.1.2-post?

**Comment by gAmUssA** [comment]
@ybyzek fixed

**Comment by ybyzek** [comment]
It needs a rebase too then ;)  (If you're not sure about rebasing, you can close this PR and open a new one based off 5.1.2-post branch)

**Comment by gAmUssA** [comment]
@ybyzek figured :)
Rebased

**Comment by ybyzek** [comment]
🥇 ship it

**Pull request merged**
