### PR TITLE
DEVX-1105: Adjust the Pumba rate limit since it appears to be too agg…

### PR DESCRIPTION
**Pull request by ybyzek**
…ressive

Observation on my mac, frequency that I would encounter that problem:

• master: 1 out of N (where N is 2 or 3)
• DEVX-1105: haven’t encountered it yet, and I have run ~ 5 times

### CODE REVIEW

**Review by javabrett — COMMENTED** [review]
I’m seeing this same on both `master` and `DEVX-1105`:
```
broker-west-1 can ping broker-west-1
ERROR: broker-west-1 cannot ping broker-west-2
Please see the Troubleshooting section of the README
```
used `stop.sh` and `start.sh`

**Comment by ybyzek** [comment]
Update: I have pushed a change to the PR.  The main change is it now uses loss instead of rate.

Results: I can run the start.sh script back-to-back without failures.

If you’re willing to give it another spin, please pull the latest changes and try again.  Thank you!

**Review by javabrett — APPROVED** [review]
Demo now completes for me with this change.

**Review by rspurgeon — APPROVED** [review]
LGTM Ran demo twice both successful

**Pull request merged**
