### PR TITLE
DEVX-1791: Create librdkafka-friendly file auto-generated by dynamic …

### PR DESCRIPTION
**Pull request by ybyzek**
…ccloud-stack variables

### Description 

https://confluentinc.atlassian.net/browse/DEVX-1791

_What behavior does this PR change, and why?_

librdkafka coverage in the script that creates delta config files (from the java-friendly one created by ccloud-stack)

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Review by awalther28 — COMMENTED** [review]
I ran this locally and validated that a librdkafka.delta was created and populated correctly with values. Note, I did not use this librdkafka file with a librdkafka client.

Looking at https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md I didn't see schema.registry.url or basic.auth.user.info. Searching through the code of librdkafka, nothing turns up either. They aren't used in our [client librdkafka example](https://docs.confluent.io/platform/current/tutorials/examples/clients/docs/c.html) either. @ybyzek can you point me to some librdkafka documentation about those two configs?

**Comment by ybyzek** [comment]
@awalther28 please see https://github.com/confluentinc/examples/blob/6.1.0-post/clients/docs/includes/configs/cloud/librdkafka-sr.config which also serves as the source of truth for what is displayed in Confluent Cloud

**Review by awalther28 — APPROVED** [review]
Gotcha, I approve. The docs we have on this subject aren't the most clear imo, [this](https://docs.confluent.io/platform/current/security/basic-auth.html#basic-auth-sr) provided the most info I could find. 
I ended up digging into github issues and PRs to see more about these configs. This provided the clearest picture of why these configs aren't mentioned in the librdkafka repo https://github.com/edenhill/librdkafka/issues/2927.

**Comment by ybyzek** [comment]
@awalther28 yes, https://github.com/edenhill/librdkafka/issues/2927#issuecomment-640565730 does provide a good synopsis.

**Pull request merged**
