### PR TITLE
bump clients and connect-streams to confluent v3.5.0

### PR DESCRIPTION
**Pull request by bbejeck**
bump clients/consumer, clients/producer and connect-streams examples to confluent version 3.5.0-SNAPSHOT

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @guozhangwang @dguy @mjsax @miguno @enothereska

**Comment by mjsax** [comment]
Don't understand this. Why is 3.4 incorrect?

**Comment by bbejeck** [comment]
Nothing is, but I thought all confluent versions on master needed to point to 3.5.0-SNAPSHOT.

**Comment by ewencp** [comment]
@mjsax master branches are on 3.5.0-SNAPSHOT, we have a separate 3.4.x branch for 3.4 versions.

**Comment by mjsax** [comment]
Ok. Thanks for clarification. (Still confusion to have 3.4 and 3.5 in parallel...)

**Pull request merged**
