### PR TITLE
Added Application Reset Example and Integration Test

### PR DESCRIPTION
**Pull request by mjsax**
@guozhangwang @miguno 
This is follow up to #60

### CODE REVIEW

**Comment by miguno** [comment]
We should also update the README.md to list the new App Reset example.

**Comment by miguno** [comment]
I gave it a cursory look only @mjsax.  I understand that most changes are javadoc formatting and code style formatting.

**Comment by mjsax** [comment]
@miguno @guozhangwang Updated README.
All JavaDoc changes are the same as in #60 and got approved by you there.
This PR basically adds two files: ApplicationResetExample.java and ApplicationResetIntegrationTest.java (as of #60 )

**Comment by mjsax** [comment]
Btw: we might want to cherry pick the README update to `3.0.1` branch, too.

**Comment by mjsax** [comment]
Build fails with
```
[ERROR] Failed to execute goal on project streams-examples: Could not resolve dependencies for project io.confluent:streams-examples:jar:3.1.0-SNAPSHOT: Failed to collect dependencies at io.confluent:kafka-avro-serializer:jar:3.1.0-SNAPSHOT: Failed to read artifact descriptor for io.confluent:kafka-avro-serializer:jar:3.1.0-SNAPSHOT: Could not transfer artifact io.confluent:kafka-avro-serializer:pom:3.1.0-SNAPSHOT from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org: Unknown host nexus.codehaus.org -> [Help 1]
```

Any ideas?

**Comment by miguno** [comment]
@mjsax The build for `master` always fails atm because there are no `3.1.0-SNAPSHOT` artifacts of any CP components available in the maven repos used by this build.

**Comment by miguno** [comment]
> Btw: we might want to cherry pick the README update to 3.0.1 branch, too.

@mjsax : yeah, feel free to do that.

**Comment by miguno** [comment]
LGTM

**Comment by guozhangwang** [comment]
@mjsax I'm about to merge it but it seems have some conflicts with the target branch: `master`, could you double check?

**Comment by mjsax** [comment]
@guozhangwang rebased.

**Comment by guozhangwang** [comment]
@mjsax Could you submit a PR for `3.1.x` branch as well (the current `kafka-0.10.1.0-cp-3.0.1` should really be renamed to `3.1.x` to follow the branch name instructions I think).

**Comment by mjsax** [comment]
This was merged to `kafka-0.10.1.0-cp-3.0.1` originally in https://github.com/confluentinc/examples/pull/60 (this PR is the second one, to get it into master, too)

**Comment by guozhangwang** [comment]
Ah I was referring to the README updates you mentioned earlier..

**Comment by mjsax** [comment]
Did this already: #71

**Pull request merged**
