### PR TITLE
Update rbac docker example readme for clarity

### PR DESCRIPTION
**Pull request by ElizabethSchafle**
Added some changes that would have been helpful to me when I started working with RBAC in the beginning, clarifying on the general syntax of defining and listing roles, as well as clarifying what roles and resources are available for ease of use.

### CODE REVIEW

**Review by ybyzek — CHANGES_REQUESTED** [review]
@ElizabethSchafle thanks for the PR.  

Since there are two separate READMEs (one for the Docker version of the RBAC demo and one for the non-Docker version of the RBAC demo), can you please also add your comments to https://github.com/confluentinc/examples/blob/5.3.0-post/security/rbac/README.md

(note: future work item is to merge these two demos and merge the two READMEs)

**Comment by ElizabethSchafle** [comment]
> https://github.com/confluentinc/examples/blob/5.3.0-post/security/rbac/README.md

for sure!

**Comment by ElizabethSchafle** [comment]
> @ElizabethSchafle thanks for the PR.
> 
> Since there are two separate READMEs (one for the Docker version of the RBAC demo and one for the non-Docker version of the RBAC demo), can you please also add your comments to https://github.com/confluentinc/examples/blob/5.3.0-post/security/rbac/README.md
> 
> (note: future work item is to merge these two demos and merge the two READMEs)

done: https://github.com/confluentinc/examples/pull/250

**Review by ybyzek — APPROVED** [review]
Thanks for the PR @ElizabethSchafle

**Pull request merged**
