### PR TITLE
Updates for 7.4 and CLI v 3.x changes

### PR DESCRIPTION
**Pull request by bbejeck**
### Description 

This PR updates the RBAC example for 7.4.0 and CLI v 3.x

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter. Please note submitters are expected to build docs-platform locally to validate before merging from examples._

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Review by kc596 — APPROVED** [review]

**Comment by kc596** [comment]
Does this change updates the docs (delta-configs) as well @ https://docs.confluent.io/platform/current/tutorials/examples/security/rbac/docs/index.html#stop-example ?

**Comment by bbejeck** [comment]
> Does this change updates the docs (delta-configs) as well @ https://docs.confluent.io/platform/current/tutorials/examples/security/rbac/docs/index.html#stop-example ?

Good catch! I missed that initially, and I'll update the docs as part of this PR.

**Comment by cherylws** [comment]
I built platform referencing this PR and it built, and looks good. Examples:
image
image

**Review by davetroiano — APPROVED** [review]
LGTM!

**Pull request merged**
