### PR TITLE
DEVX-2159: set KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR=1 to…

### PR DESCRIPTION
**Pull request by ybyzek**
… avoid (non-functionality-impacting) error in broker logs

This demo was missed by   DEVX-2013 

```
kafka | [2020-10-06 12:52:04,798] ERROR Unexpected error when checking for _confluent_balancer_partition_samples topic existence. (com.linkedin.kafka.cruisecontrol.SbkTopicUtils)
kafka | [2020-10-06 12:52:04,862] ERROR Error when checking for sample store topics: java.lang.IllegalStateException: Kafka cluster has 1 brokers but the requested replication factor is 3 (brokers in cluster=1, zookeeper.connect=zookeeper:2181) (com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore)
kafka | [2020-10-06 12:52:04,862] ERROR Error: (com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore)
```

Validated that the error messages go away with this fix

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM

**Comment by gianlucanatali** [comment]
Hi, I have tested this branch and I could now see 2 clusters in C3, both healthy initially:
image

 But then:
image


- I can see the list of topics with ccloud cli: ✅  
- view pageview topics in C3 ❌
- view users topic in C3 ccloud cluster: ✅ I can see the data, but it takes a few seconds after the No message text shows up. Might be worth calling that out in the demo docs as expected behavior?
- see ksqlDB flow in CCloud UI, and inspect messages : ✅
- check replicator config ✅
- check pageviews messages in CCloud UI: ❌ No messages are coming in . If I select partition 0 I can see some data in though
image
- see replicator lag in CCloud UI: ✅
- check pageviews schema from CCloud UI ✅
- Attached the log file from docker-compose
[demo.log](https://github.com/confluentinc/examples/files/5335663/demo.log)

**Comment by ybyzek** [comment]
@gianlucanatali this level of detail is wonderful, thank you for detailed notes.  

This PR was meant to address something different (DEVX-2159 for ERRORs in logs, which are now resolved).  Can you please add these notes to the jira DEVX-2158 ?  (or if you prefer, I can, please let me know).

**Comment by gianlucanatali** [comment]
Hi @ybyzek , sure will add the details there , sorry for the confusion!

**Comment by ybyzek** [comment]
Thanks so much @gianlucanatali 🥇

**Pull request merged**
