### PR TITLE
Remove hardcoded avro version

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-2617

Just specifying the serializer dependency should transitively bring in the correct Avro version.
No need to hardcode it (which would have obviated other issues encountered)

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] clients/cloud

- [x] connect-streams-pipeline

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Changes look good, but should we also remove the actual Avro dependency declarations that reference the specified version? For example, in `connect-streams-pipeline/pom.xml`:

```
     <dependency>
       <groupId>org.apache.avro</groupId>
       <artifactId>avro</artifactId>
       <version>${avro.version}</version>
     </dependency>
```

**Comment by ybyzek** [comment]
@mikebin thank you, I didn't realize that entire dependency could be removed (versus inheriting the `avro.version` variable).  Corrected in latest commit.

**Review by ghost — APPROVED** [review]
LGTM

**Review by rspurgeon — APPROVED** [review]
lgtm

**Pull request merged**
