### PR TITLE
DEVX-2275 add suggested resources links to tutorial

### PR DESCRIPTION
**Pull request by evanbates**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-2275

_What behavior does this PR change, and why?_

Adds a collection of suggested resources to tutorial.

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

None

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

 Documentation

### CODE REVIEW

**Comment by ybyzek** [comment]
@evanbates thanks for the PR!

1. Does the docs build pass or would you like me to do a local build verification?
2. I've tagged the @confluentinc/docs team for additional review

**Comment by evanbates** [comment]
@ybyzek Thanks for the review! 
1. Would it be possible to check the local build this time? (I await Artifactory access). It would be much appreciated!

**Comment by ybyzek** [comment]
@evanbates local build passes.

**Comment by evanbates** [comment]
@ybyzek Great, thank you!

**Review by tobydrake7 — APPROVED** [review]

**Review by ybyzek — APPROVED** [review]

**Pull request merged**
