### PR TITLE
update pom to 3.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by bbejeck**

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @mjsax @guozhangwang missed the pom setting during the restore.

**Comment by guozhangwang** [comment]
Should the jenkins failure still happen with your fix?

```
[ERROR] Failed to execute goal on project streams-examples: Could not resolve dependencies for project io.confluent:streams-examples:jar:3.4.0-SNAPSHOT: The following artifacts could not be resolved: io.confluent:kafka-streams-avro-serde:jar:3.4.0-SNAPSHOT, io.confluent:kafka-avro-serializer:jar:3.4.0-SNAPSHOT, io.confluent:kafka-schema-registry-client:jar:3.4.0-SNAPSHOT, org.apache.kafka:kafka-clients:jar:0.11.0.0-SNAPSHOT, org.apache.kafka:kafka-streams:jar:0.11.0.0-SNAPSHOT, org.apache.kafka:kafka_2.11:jar:0.11.0.0-SNAPSHOT, org.apache.kafka:kafka_2.11:jar:test:0.11.0.0-SNAPSHOT, org.apache.kafka:kafka-clients:jar:test:0.11.0.0-SNAPSHOT, org.apache.kafka:kafka-streams:jar:test:0.11.0.0-SNAPSHOT, io.confluent:kafka-schema-registry:jar:3.4.0-SNAPSHOT, io.confluent:kafka-schema-registry:jar:tests:3.4.0-SNAPSHOT: Could not find artifact io.confluent:kafka-streams-avro-serde:jar:3.4.0-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by guozhangwang** [comment]
The change itself lgtm.

**Comment by bbejeck** [comment]
I thought those dependency issues were resolved.  This update needs to go in, I'll follow up if the tests fail.

**Pull request merged**
