### PR TITLE
fixing issue on 'SchemaRegistryClient' object has no attribute 'strip'

### PR DESCRIPTION
**Pull request by chunyeow**
Signed-off-by: Chun-Yeow Yeoh <yeohchunyeow@gmail.com>

### Description 

Having an issue as documented here [1]. Fix this.

[1] https://github.com/confluentinc/examples/issues/973

### CODE REVIEW

**Review by edenhill — APPROVED** [review]
LGTM

**Comment by ybyzek** [comment]
@rspurgeon would you be able to validate the PR?

**Review by rspurgeon — APPROVED** [review]
LGTM

Verified:
```
./producer_ccsr.py -f ~/dev/confluentinc/examples/ccloud/ccloud-stack/stack-configs/java-service-account-214623.config -t test1
Producing Avro record: alice    0
Producing Avro record: alice    1
Producing Avro record: alice    2
Producing Avro record: alice    3
Producing Avro record: alice    4
Producing Avro record: alice    5
Producing Avro record: alice    6
Producing Avro record: alice    7
Producing Avro record: alice    8
Producing Avro record: alice    9
Produced record to topic test1 partition [0] @ offset 0
Produced record to topic test1 partition [0] @ offset 1
Produced record to topic test1 partition [0] @ offset 2
Produced record to topic test1 partition [0] @ offset 3
Produced record to topic test1 partition [0] @ offset 4
Produced record to topic test1 partition [0] @ offset 5
Produced record to topic test1 partition [0] @ offset 6
Produced record to topic test1 partition [0] @ offset 7
Produced record to topic test1 partition [0] @ offset 8
Produced record to topic test1 partition [0] @ offset 9
10 messages were produced to topic test1!
```

**Comment by ybyzek** [comment]
Thanks y'all! 🏅

**Pull request merged**
