### PR TITLE
DEVX-1761: CCloud demo: create custom connect topic names so that the…

### PR DESCRIPTION
**Pull request by ybyzek**
…y can be deleted at the end

### CODE REVIEW

**Review by daveshook — COMMENTED** [review]
LGTM

**Comment by rspurgeon** [comment]
@ybyzek I still don't fully understand the demo hierarchy under this folder so I'm not certain which files pertain to which demo... do the two datagen clients, which I believe target the cloud cluster, also need to be updated?

```
./clients/kafka-connect-datagen/docker-compose.yml:16:      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
./clients/ksql-datagen/docker-compose.yml:49:      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
```

What about the delete topics command?
```
./ccloud-delete-all-topics.sh:24:topics_to_delete="_schemas connect-configs connect-status connect-statuses connect-offsets"
```

**Comment by ybyzek** [comment]
@rspurgeon fair point.  This PR targets _only_ the ccloud demo; the datagens are out of scope.

**Review by rspurgeon — APPROVED** [review]
LGTM

**Pull request merged**
