### PR TITLE
DEVX-2734: prebuild producer/consumer in demo client image

### PR DESCRIPTION
**Pull request by javabrett**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-2734

_What behavior does this PR change, and why?_

In `examples/ccloud-observability`, once the cloud-stack/cluster has been created, Docker containers are launched for a producer and consumer, to create demo-topic-1 and some suitable metrics traffic.

Currently, the image build for `cnfldemos/ccloud-observability-client:0.1.0` stops after some basic Maven and source setup - no build is done, and more importantly no dependencies are downloaded.  These two steps are deferred until container launch-time, when `mvn ... exec:java` is run against unbuilt source.

This PR changes the Docker image build so that it includes the potentially-slow process of resolving all the dependencies, then executes the build ... making the run producer/consumer steps almost instant launches.

**Testing**

You can run the Observability demo as-is, and use `docker logs` to note that the producer/consumer takes time to build/launch (mostly pulling deps), and that during that time the demo Grafana dashboard is pretty ineffective.

To test the PR, you need to run `make build-image` then run as normal.

Post merge we will need to verify that the containers build ran and pushed a new image version to Docker Hub.

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [X] ccloud-observability

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Review by davetroiano — APPROVED** [review]
change LGTM, thanks @javabrett! one thing I don't follow:

>Post merge we will need to verify that the containers build ran and pushed a new image version to Docker Hub.

I think that we need to push to Dockerhub pre-merge to keep the demo working from external (docs) perspective - since docs tell users to checkout `7.2.2-post` and run `start.sh`

**Comment by javabrett** [comment]
> I think that we need to push to Dockerhub pre-merge to keep the demo working from external (docs) perspective - since docs tell users to checkout 7.2.2-post and run start.sh

Agreed, pre-merge is better.  I was highlighting that I don't have access to do that, and don't know if there's an automated build.  So if it can be done from the PR branch ahead of the build, otherwise need someone with access on-standby.

**Comment by davetroiano** [comment]
> So if it can be done from the PR branch ahead of the build

ah, ok. There's no automated push. I just pushed it (see [here](https://hub.docker.com/layers/cnfldemos/ccloud-observability-client/0.2.0/images/sha256-c0d4101b153f836283b52ca72b57295ec3945aef83d0c4058d018824eb6f1ffd?context=explore))

I pushed a couple of commits to your branch to get this done. Notably, I replaced `confluent-log4j` with `reload4j` bc I hit this error when building the image:

```
#12 41.00 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
#12 41.00 [ERROR] 'dependencies.dependency.version' for io.confluent:confluent-log4j:jar is missing. @ line 91, column 21
#12 41.00  @
#12 41.00 [ERROR] The build could not read 1 project -> [Help 1]
#12 41.00 [ERROR]
#12 41.00 [ERROR]   The project io.confluent:clients-example:7.2.2 (/tmp/java/pom.xml) has 1 error
#12 41.00 [ERROR]     'dependencies.dependency.version' for io.confluent:confluent-log4j:jar is missing. @ line 91, column 21
#12 41.00 [ERROR]
#12 41.00 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#12 41.00 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#12 41.00 [ERROR]
#12 41.00 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#12 41.00 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

Did it build for you??

I'm guessing that this worked in previous versions due to Maven `dependencyManagement` handling `io.confluent:confluent-log4`'s version elsewhere in a parent POM, and that that has since been removed from the parent. I didn't chase the theory down but I think that moving to reload4j is the right move -- it seems to be what's happening generally across Confluent repos.

If for any reason you don't want 0.2.0 to reflect this branch as of the time of this comment, let me know and I can push another

**Comment by javabrett** [comment]
> Did it build for you??

Good catch @davetroiano.  It did previously when the PR was first made, but as you suggest, some dependency upstream has changed.  Your `reload4j` sub LGTM.

This is in a much better state now - thanks for the review and the image push.  The demo now works straight after startup.

**Pull request merged**
